---
- name: install windows applciations
  hosts: windows
  tasks:
    - name: Install Firefox
      win_chocolatey:
       name: firefox
       state: present
    - name: Install 7zip
      win_chocolatey:
       name: 7zip
       state: present
